### ISSUE TITLE
arduino-builder doesn't use platform.keys.rewrite

### ISSUE THREAD

**Issue by iglosiggio** [rockstorm101/arduino-builder-debian-pkg#2]
arduino-builder loads `platform.keys.rewrite.txt` relative to the `-hardware` flag given. In the case of the Arduino IDE this is `/usr/share/arduino`.

As i've yet to understand how the builder works i don't know if moving everything in the `hardware` folder from arduino is better than moving everything to `/usr/share/arduino-builder`.

**Comment by rockstorm101** [comment]
I would suggest symlinking whatever is needed of the arduino-builder package from /usr/share/arduino. Avoid duplication if possible.

**Comment by iglosiggio** [comment]
Seems like a good idea :+1:
